export default {
  bigStat: [
    {
      product: 'Light Blue',
      total: '4,232',
      color: 'primary',
      registrations: {
        value: 830,
        profit: true,
      },
      bounce: {
        value: 4.5,
        profit: false,
      },
    },
    {
      product: 'Sing App',
      total: '754',
      color: 'danger',
      registrations: {
        value: 30,
        profit: true,
      },
      bounce: {
        value: 2.5,
        profit: true,
      },
    },
    {
      product: 'RNS',
      total: '1,025',
      color: 'info',
      registrations: {
        value: 230,
        profit: true,
      },
      bounce: {
        value: 21.5,
        profit: false,
      },
    },
  ],
  table: [
    {
      id: 0,
      name: 'Bellview Estate',
      groups: 5,
      product: 'ON the Road',
      price: '₦ 10,000,000',
      date: '11 May 2017',
      city: 'Otsego',
      status: 'Active',
    },
    {
      id: 1,
      name: 'Amen Estate',
      groups: 7,
      product: 'HP Core i7',
      price: '₦ 15,000,000',
      date: '4 Jun 2017',
      city: 'Fivepointville',
      status: 'Active',
    },
    {
      id: 2,
      name: 'Lekki Foreshore',
      groups: 4,
      product: 'Air Pro',
      price: '₦ 7,050,000',
      date: '27 Aug 2017',
      city: 'Leadville North',
      status: 'Inactive',
    },
    {
      id: 3,
      name: 'Super Mall',
      groups: 10,
      product: 'Version Control',
      price: '₦ 45,000,000',
      date: '19 Feb 2018',
      city: 'Seaforth',
      status: 'Inactive',
    },
    {
      id: 4,
      name: 'Hollandas Hotel',
      groups: 15,
      product: 'Let\'s Dance',
      price: '₦ 11,000,500',
      date: '1 Mar 2018',
      city: 'Hanoverton',
      status: 'Active',
    },
    {
      id: 5,
      name: 'Eko Atlantic',
      groups: 10,
      product: 'Air Pro',
      price: '₦ 115,500,000',
      date: '27 Aug 2017',
      city: 'Leadville North',
      status: 'Active',
    },
    {
      id: 6,
      name: 'Changwey Yatch',
      groups: 3,
      product: 'Version Control',
      price: '₦ 38,350,000',
      date: '19 Feb 2018',
      city: 'Seaforth',
      status: 'Inactive',
    },
    {
      id: 7,
      name: 'Bajas Sky scraper',
      groups: 11,
      product: 'Let\'s Dance',
      price: '₦ 56,000,500',
      date: '1 Mar 2018',
      city: 'Hanoverton',
      status: 'Active',
    },
  ],
};
